apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-tls
  namespace: media
spec:
  secretName: tautulli-tls
  issuerRef:
    name: step-ca-acme-external
    kind: ClusterIssuer
  dnsNames:
    - media.homelab.local
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
