apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: media
  labels:
    app: tautulli
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
