apiVersion: v2
name: cert-manager-wrapper
description: A wrapper chart for cert-manager
type: application
version: 0.1.0
appVersion: "1.19.2"
dependencies:
  - name: cert-manager
    version: v1.19.2
    repository: https://charts.jetstack.io
