---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: step-ca-acme
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: argo.homelab.local
  dnsNames:
    - argo.homelab.local
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
