apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: duckietv
  namespace: duckietv
  labels:
    app: duckietv
spec:
  running: true
  template:
    metadata:
      labels:
        app: duckietv
        vm.kubevirt.io/name: duckietv
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: "8Gi"
        devices:
          inputs:
            - type: tablet
              name: tablet
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 3000
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:40
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
              - dnf install -y xorg-x11-server-Xvfb x11vnc xfce4-session xfce4-panel xfce4-settings xfwm4 xfce4-terminal git nodejs npm
              - # Create a startup script for the desktop
              - echo '#!/bin/bash' > /usr/local/bin/start-desktop.sh
              - echo 'export DISPLAY=:0' >> /usr/local/bin/start-desktop.sh
              - echo 'rm -f /tmp/.X0-lock' >> /usr/local/bin/start-desktop.sh
              - echo 'Xvfb :0 -screen 0 1280x1024x24 &' >> /usr/local/bin/start-desktop.sh
              - echo 'sleep 5' >> /usr/local/bin/start-desktop.sh
              - echo 'startxfce4 &' >> /usr/local/bin/start-desktop.sh
              - echo 'x11vnc -display :0 -forever -nopw -rfbport 3000' >> /usr/local/bin/start-desktop.sh
              - chmod +x /usr/local/bin/start-desktop.sh
              - /usr/local/bin/start-desktop.sh &
