apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: duckietv
  namespace: duckietv
  labels:
    app: duckietv
spec:
  running: true
  template:
    metadata:
      labels:
        app: duckietv
        vm.kubevirt.io/name: duckietv
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: "4Gi"
        devices:
          inputs:
            - type: tablet
              name: tablet
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 3000
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      readinessProbe:
        tcpSocket:
          port: 3000
        initialDelaySeconds: 60
        periodSeconds: 10
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: duckietv-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            # Ensure the disk grows to 10GB
            growpart:
              mode: auto
              devices: ['/']
            resize_fs:
              enabled: true
              device: /
            runcmd:
              - |
                cat <<'EOF' > /usr/local/bin/setup-duckie.sh
                #!/bin/bash
                exec > /var/log/duckie-setup.log 2>&1
                set -x
                export DEBIAN_FRONTEND=noninteractive
                
                # Wait for network
                until ping -c 1 google.com; do sleep 2; done
                
                # Install Desktop and VNC
                apt-get update
                apt-get install -y xfce4 x11vnc xvfb git nodejs npm novnc websockify
                
                # Setup Display
                Xvfb :0 -screen 0 1280x1024x24 &
                sleep 5
                DISPLAY=:0 startxfce4 &
                
                # Start VNC
                x11vnc -display :0 -forever -nopw -rfbport 5900 &
                
                # Start noVNC (Correct Ubuntu path)
                /usr/bin/novnc_proxy --vnc localhost:5900 --listen 3000 &
                
                # DuckieTV
                git clone https://github.com/SchizoDuckie/DuckieTV.git /opt/DuckieTV
                cd /opt/DuckieTV && npm install
                EOF
                chmod +x /usr/local/bin/setup-duckie.sh
                /usr/local/bin/setup-duckie.sh &
  dataVolumeTemplates:
  - metadata:
      name: duckietv-root
      annotations:
        cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    spec:
      storage:
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
      source:
        registry:
          url: "docker://quay.io/containerdisks/ubuntu:22.04"