apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: duckietv
  namespace: duckietv
  labels:
    app: duckietv
spec:
  running: true
  template:
    metadata:
      labels:
        app: duckietv
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: "4Gi"
        devices:
          inputs:
            - type: tablet
              name: tablet
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 3000
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
              - apt-get update
              - apt-get install -y xfce4 xfce4-goodies x11vnc xvfb git nodejs npm
              - # Set up a virtual display and start VNC on port 3000 for Traefik
              - Xvfb :0 -screen 0 1280x1024x24 &
              - export DISPLAY=:0
              - startxfce4 &
              - x11vnc -display :0 -forever -nopw -rfbport 3000 &
              - # Install DuckieTV
              - git clone https://github.com/SchizoDuckie/DuckieTV.git /opt/DuckieTV
              - cd /opt/DuckieTV && npm install