apiVersion: v1
kind: Service
metadata:
  name: duckietv
  namespace: duckietv
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    # This is the verified label from the pod
    vm.kubevirt.io/name: duckietv
  type: ClusterIP
