apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: duckietv
  namespace: duckietv
  labels:
    app: duckietv
spec:
  running: true
  template:
    metadata:
      labels:
        app: duckietv
        vm.kubevirt.io/name: duckietv
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: "4Gi"
        devices:
          inputs:
            - type: tablet
              name: tablet
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 3000
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      # The Guru move: Don't let Traefik talk to us until the VNC server is READY
      readinessProbe:
        tcpSocket:
          port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
              - export DEBIAN_FRONTEND=noninteractive
              - apt-get update
              - apt-get install -y xfce4 x11vnc xvfb git nodejs npm
              - # Start the virtual desktop
              - Xvfb :0 -screen 0 1280x1024x24 &
              - sleep 5
              - DISPLAY=:0 startxfce4 &
              - # Start VNC on port 3000 (mapped to the pod port)
              - x11vnc -display :0 -forever -nopw -rfbport 3000 &
              - # Clone and install DuckieTV
              - git clone https://github.com/SchizoDuckie/DuckieTV.git /opt/DuckieTV
              - cd /opt/DuckieTV && npm install