apiVersion: v1
kind: Service
metadata:
  name: duckietv
  namespace: duckietv
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    # Using the native KubeVirt label for better accuracy
    kubevirt.io/domain: duckietv
  type: ClusterIP