---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: unifi-headers
  namespace: unifi
spec:
  headers:
    customRequestHeaders:
      Authorization: ""
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "unifi.homelab.local"
      X-Forwarded-Port: "443"
