---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
