---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-mongodb
  namespace: unifi
  labels:
    app: unifi-mongodb
type: Opaque
stringData:
  # NOTE: Change this password in production and use a secrets manager
  password: "unifi-mongo-password-change-me"
