apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  issuerRef:
    name: step-ca-acme-external
    kind: ClusterIssuer
  commonName: vault.vault.svc
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-active
    - vault-active.vault
    - vault-active.vault.svc
    - vault-active.vault.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
