---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: node-exporter-exceptions
  namespace: monitoring
spec:
  exceptions:
  - policyName: require-non-root-user
    ruleNames:
    - check-runAsNonRoot
    - autogen-check-runAsNonRoot
  - policyName: require-readonly-rootfs
    ruleNames:
    - check-readonlyRootFilesystem
    - autogen-check-readonlyRootFilesystem
  - policyName: pod-security-baseline
    ruleNames:
    - disallow-privilege-escalation
    - drop-all-capabilities
    - autogen-disallow-privilege-escalation
    - autogen-drop-all-capabilities
    - disallow-host-namespaces
    - autogen-disallow-host-namespaces
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - monitoring
        names:
        - node-exporter*
